# Save and Load Trained Model using Pickle

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("newh.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
newm= linear_model.LinearRegression()
newm.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
newm.coef_

array([135.78767123])

In [5]:
newm.intercept_

180616.43835616432

In [7]:
newm.predict([[4750]])

array([825607.87671233])

using pickle we can save the model

In [8]:
import pickle

In [9]:
with open('new_train_model','wb') as file:
    pickle.dump(newm,file)

use pickle model

In [12]:
with open('new_train_model','rb') as linear:
    nm = pickle.load(linear)

In [13]:
nm.coef_

array([135.78767123])

In [15]:
nm.intercept_

180616.43835616432

In [16]:
nm.predict([[4750]])

array([825607.87671233])

Using joblib we can also save the model

In [17]:
from sklearn.externals import joblib

C:\conda\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [19]:
joblib.dump(newm, 'new_model_joblib')

['new_model_joblib']

load joblib model

In [20]:
nejob = joblib.load('new_model_joblib')

In [21]:
nejob.coef_

array([135.78767123])

In [22]:
nejob.intercept_

180616.43835616432

In [23]:
nejob.predict([[4750]])

array([825607.87671233])