# KFold Cross Validation

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

We are checking above models accuracy using cross validation

In [23]:
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.25)

In [25]:
lg = LogisticRegression(solver='liblinear',multi_class='ovr')
lg.fit(X_train, y_train)
lg.score(X_test, y_test)

0.9466666666666667

In [26]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3

In [27]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9622222222222222

In [49]:
from sklearn.model_selection import KFold
kfc = KFold(n_splits=3)
kfc

KFold(n_splits=3, random_state=None, shuffle=False)

In [50]:
for train_index, test_index in kfc.split([11,22,33,44,55,66,77,88,99]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
from sklearn.model_selection import cross_val_score

In [35]:
scores1=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)
scores1

array([0.89482471, 0.95325543, 0.90984975])

In [36]:
np.average(scores1)

0.9193099610461881

In [37]:
score2=cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)
score2

array([0.38063439, 0.41068447, 0.51252087])

In [40]:
np.average(score2)

0.4346132442960489

In [42]:
score3=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)
score3

array([0.93155259, 0.94991653, 0.92654424])

In [43]:
np.average(score3)

0.9360044518642181

In [44]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.8764773432650529

In [51]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.9204220980757292

In [52]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=15),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.9282371198013655

In [53]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.9432216014897579

In [54]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.9515642458100558

In [55]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)#change number of tress
np.average(scores1)

0.9471446306641838